### ISSUE TITLE
Zenihth Demo Review # 1 Demo page 1

### ISSUE THREAD

**Issue by clahban** [ZENITH-Intelligence/ZENITH-Intelligence.github.io#15]
1. To access the demo, one first has to be granted access, via the sign up/ sign in page. 
2. The text in use case section overlaps 
 ![image](https://github.com/user-attachments/assets/2b5305e2-07ec-4c21-aaa3-49ce9b11c105) 
3. Could add a view more bellow the heading so the paragraph is accessed by clinking the 3dots to view the remainder of the text. You can also reference the figma design, as this is also somewhat unaligned on the page
 ![image](https://github.com/user-attachments/assets/5a5022ff-d136-4edd-b681-6d5bcc39b8b4)

**Comment by NicholasS13** [comment]
made sign in page index.html and moved demo-1 to separate file, will implement login backend/verification shortly

**Comment by NicholasS13** [comment]
#4 issue same as 2 here

**Comment by NicholasS13** [comment]
login to demo 1 redirect implemented, need to implement login verication backend and one time passcode still

**Comment by NicholasS13** [comment]
closing because the remaining parts of this issue are in other issues on issue block, reopen if not the case
